fail_fast: false
exclude: ^.*\b(migrations)\b.*$
repos:


-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: [
            --in-place,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --remove-unused-variables,
        ]

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
     -   id: black
         language_version: python3.12
         args: ['-S'] # -S  не смотреть в локальные настройки, только CLI и hook



-  repo: https://github.com/myint/docformatter
   rev: v1.7.5
   hooks:
     - id: docformatter
       args: [
           --in-place,
           --blank,
       ]

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.8
#    hooks:
#     -   id: mypy
#         args: [--ignore-missing-imports]

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [
          --config=.flake8,
          --max-line-length=120,

          # E203 whitespace before ':'  that added by "black" in slices
          # https://github.com/psf/black/blob/06ccb88bf2bd35a4dc5d591bb296b5b299d07323/docs/guides/using_black_with_other_tools.md#flake8
          --extend-ignore=E203,
          # allow to use random module
          --extend-ignore=DUO102

        ]
        exclude: .git|__pycache__
        additional_dependencies:
          - flake8-builtins>=1.5.3
          - flake8-debugger>=4.0.0
          - flake8-comprehensions>=3.3.1
          - flake8-eradicate>=1.0.0
          - dlint>=0.11.0

-   repo: https://github.com/milin/giticket
    rev: v1.4
    hooks:
      - id:  giticket
        args: ['--regex=[A-Za-z]+-\d+', '--format={ticket} {commit_msg}']